### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by pr0zitiv** [Displax/modem-fix#1]
poco x3 nfc (surya)
crDroid 8.11 (android 12)
Magisk Delta (https://huskydg.github.io/magisk-files/)
Zygisk выключен

Universal Modern Fix
by Displax [4PDAJ
Powered by Magisk
Extracting module files
- Installing from Magisk app
- Magisk version: 25206
- Device is: surya
- CFG version is:
CFG file is in the state;
- Your device i config file or ROM build unsupported ye
. Installation failed

**Comment by Displax** [comment]
Модуль только для пикселей с SoC Tensor
