### ISSUE TITLE
Нет сети после июньского обновления

### ISSUE THREAD

**Issue by DiofyZz** [Displax/modem-fix#5]
После июньского обновления нет сети на симках билайн и теле2, думаю проблема глобальная и на других операторах должно быть то же самое. После отключения модуля всё работает как надо.

**Comment by Displax** [comment]
Модем новый, соответственно не работает. Будет обновление

**Comment by Displax** [comment]
https://github.com/Displax/modem-fix/commit/08e5954d7bb782d7b140dc63e8f8fccd2851173c

**Comment by Zerogoki00** [comment]
Все равно нет сети даже после обновления
