### ISSUE TITLE
Installation fails on Pixel 7a for Release 1.8

### ISSUE THREAD

**Issue by dimitris614** [Displax/modem-fix#7]
![Screenshot_20230618-201348](https://github.com/Displax/modem-fix/assets/136994416/842e1790-53b7-4d75-a19a-34a5ba55525b)

**Comment by Displax** [comment]
Pixel 7a is not supported yet.

**Comment by dimitris614** [comment]
Thank you for your response and your effort. Please support Pixel 7a in your next release.

**Comment by Filosofdj** [comment]
> Pixel 7a is not supported yet.

And Pixel 6 pro (Android 14 beta 3) is not supported yet. 
UPB3.230519.014

**Comment by Displax** [comment]
https://github.com/Displax/modem-fix/commit/eaf1370c34a6c35df52640fa139e98250185a36f
